import { cn } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-Dana bg-background text-foreground antialiased max-w-full overflow-x-hidden",)}
      >
        {children}
      </body>
    </html>
  );
}
